Repository orange-cloudavenue/terraform-plugin-framework-supertypes, pull requests merged in 2025-03, with the labels that each got.

#30 feat: Add generic Encode/Decode func (beta)
  .gitignore
  .pre-commit/go-mod
  encode_decode.go
  single_nested_value.go
  templates/single_nested_type.go.tmpl
  templates/single_nested_value.go.tmpl
Labels: size/M, feature

#33 feat: Add generic Encode/Decode func (beta)
  encode_decode.go
Labels: size/XS, feature

#35 chore: add codeowner file
  .github/CODEOWNERS
Labels: size/XS, chore

#36 feat: add `MustGet/Set` & `DiagsGet/Set`
  .changelog/36.txt
  README.md
  bool_value.go
  errs.go
  float64_value.go
  int32_value.go
  int32_value_test.go
  int64_value.go
  list_nested_value.go
  list_value.go
  map_nested_value.go
  map_value.go
  object_value.go
  set_nested_value.go
  set_value.go
  single_nested_value.go
  string_value.go
  templates/array_value.go.tmpl
  templates/nested_value.go.tmpl
  templates/object_value.go.tmpl
  templates/simple_value.go.tmpl
  templates/single_nested_value.go.tmpl
Labels: feature, size/L

#38 chore: synced file(s) with orange-cloudavenue/workflows
  .golangci.yml
  .taskfiles/README.md
  .taskfiles/golang.yml
  .taskfiles/internal.yml
  .taskfiles/license.yml
  .taskfiles/pre-commit.yml
  .taskfiles/terraform.yml
  .taskfiles/yaml.yml
  Taskfile.yml
Labels: sync, size/M, chore

#39 fix: add missing int32 and float32 types
  .changelog/39.txt
  attrtypes.go
  attrtypes_test.go
Labels: size/S, fix
